// Generated by scripts/lidar/export_visibility_regions.py.
// Do not edit by hand; regenerate it from the published manifests.

export const URBAN_UNIT_VISIBILITY_REGIONS = [
  {
    "rank": 2,
    "code": "00760",
    "slug": "lyon",
    "name": "Lyon",
    "id": "uu-00760-maximum-geometry",
    "version": "uu-00760-2026-max-v1",
    "label": "Unité urbaine de Lyon",
    "sourceNotes": "Composition INSEE des UU 2020 au 01/01/2026 ; contours communaux Etalab 2026 (Admin Express IGN), précision 5 m.",
    "coverage": {
      "north": 46.047089283742885,
      "south": 45.518304638583125,
      "east": 5.102293276611932,
      "west": 4.5488143655933255
    },
    "reference": {
      "mode": "fixed-instant",
      "label": "Unité urbaine de Lyon · maximum local au centroïde",
      "timeUtc": "2026-08-12T18:21:31.063Z"
    },
    "surface": {
      "resolutionMeters": 5.0,
      "observerHeightMeters": 1.7,
      "includesBuildings": true,
      "includesVegetation": true,
      "generatedAt": "2026-08-10T16:22:45.264016+00:00",
      "sourceTiers": [
        "IGN LiDAR HD",
        "MNS Correl (fallback)",
        "RGE ALTI (fallback)"
      ]
    },
    "halo": {
      "capped": false,
      "sunwardMeters": 11673.394870794442
    },
    "tiles": {
      "scheme": "xyz",
      "tileSize": 256,
      "minZoom": 8,
      "maxZoom": 15
    },
    "attribution": "© IGN — LiDAR HD, MNS Correl et RGE ALTI · Licence Ouverte 2.0"
  },
  {
    "rank": 3,
    "code": "00759",
    "slug": "marseille-aix-en-provence",
    "name": "Marseille–Aix-en-Provence",
    "id": "uu-00759-maximum-geometry",
    "version": "uu-00759-2026-max-v1",
    "label": "Unité urbaine de Marseille–Aix-en-Provence",
    "sourceNotes": "Composition INSEE des UU 2020 au 01/01/2026 ; contours communaux Etalab 2026 (Admin Express IGN), précision 5 m.",
    "coverage": {
      "north": 43.6367310225593,
      "south": 43.160460021649314,
      "east": 5.797915326160008,
      "west": 4.806721147922355
    },
    "reference": {
      "mode": "fixed-instant",
      "label": "Unité urbaine de Marseille–Aix-en-Provence · maximum local au centroïde",
      "timeUtc": "2026-08-12T18:25:00.365Z"
    },
    "surface": {
      "resolutionMeters": 5.0,
      "observerHeightMeters": 1.7,
      "includesBuildings": true,
      "includesVegetation": true,
      "generatedAt": "2026-08-10T16:23:43.827465+00:00",
      "sourceTiers": [
        "IGN LiDAR HD",
        "MNS Correl (fallback)",
        "RGE ALTI (fallback)"
      ]
    },
    "halo": {
      "capped": true,
      "sunwardMeters": 15000.0
    },
    "tiles": {
      "scheme": "xyz",
      "tileSize": 256,
      "minZoom": 8,
      "maxZoom": 15
    },
    "attribution": "© IGN — LiDAR HD, MNS Correl et RGE ALTI · Licence Ouverte 2.0"
  },
  {
    "rank": 4,
    "code": "00758",
    "slug": "toulouse",
    "name": "Toulouse",
    "id": "uu-00758-maximum-geometry",
    "version": "uu-00758-2026-max-v1",
    "label": "Unité urbaine de Toulouse",
    "sourceNotes": "Composition INSEE des UU 2020 au 01/01/2026 ; contours communaux Etalab 2026 (Admin Express IGN), précision 5 m.",
    "coverage": {
      "north": 43.856776313401795,
      "south": 43.38670711746445,
      "east": 1.601890148312011,
      "west": 1.1469273664535158
    },
    "reference": {
      "mode": "fixed-instant",
      "label": "Unité urbaine de Toulouse · maximum local au centroïde",
      "timeUtc": "2026-08-12T18:25:54.865Z"
    },
    "surface": {
      "resolutionMeters": 5.0,
      "observerHeightMeters": 1.7,
      "includesBuildings": true,
      "includesVegetation": true,
      "generatedAt": "2026-08-10T16:24:11.975528+00:00",
      "sourceTiers": [
        "IGN LiDAR HD",
        "MNS Correl (fallback)",
        "RGE ALTI (fallback)"
      ]
    },
    "halo": {
      "capped": false,
      "sunwardMeters": 4000.0
    },
    "tiles": {
      "scheme": "xyz",
      "tileSize": 256,
      "minZoom": 8,
      "maxZoom": 15
    },
    "attribution": "© IGN — LiDAR HD, MNS Correl et RGE ALTI · Licence Ouverte 2.0"
  },
  {
    "rank": 5,
    "code": "59702",
    "slug": "lille",
    "name": "Lille (partie française)",
    "id": "uu-59702-maximum-geometry",
    "version": "uu-59702-2026-max-v1",
    "label": "Unité urbaine de Lille (partie française)",
    "sourceNotes": "Composition INSEE des UU 2020 au 01/01/2026 ; contours communaux Etalab 2026 (Admin Express IGN), précision 5 m.",
    "coverage": {
      "north": 50.79464274731383,
      "south": 50.50939657954185,
      "east": 3.2735628258293175,
      "west": 2.925327335084224
    },
    "reference": {
      "mode": "fixed-instant",
      "label": "Unité urbaine de Lille (partie française) · maximum local au centroïde",
      "timeUtc": "2026-08-12T18:14:02.773Z"
    },
    "surface": {
      "resolutionMeters": 5.0,
      "observerHeightMeters": 1.7,
      "includesBuildings": true,
      "includesVegetation": true,
      "generatedAt": "2026-08-10T16:24:28.051970+00:00",
      "sourceTiers": [
        "IGN LiDAR HD",
        "MNS Correl (fallback)",
        "RGE ALTI (fallback)"
      ]
    },
    "halo": {
      "capped": false,
      "sunwardMeters": 4000.0
    },
    "tiles": {
      "scheme": "xyz",
      "tileSize": 256,
      "minZoom": 8,
      "maxZoom": 15
    },
    "attribution": "© IGN — LiDAR HD, MNS Correl et RGE ALTI · Licence Ouverte 2.0"
  },
  {
    "rank": 6,
    "code": "33701",
    "slug": "bordeaux",
    "name": "Bordeaux",
    "id": "uu-33701-maximum-geometry",
    "version": "uu-33701-2026-max-v1",
    "label": "Unité urbaine de Bordeaux",
    "sourceNotes": "Composition INSEE des UU 2020 au 01/01/2026 ; contours communaux Etalab 2026 (Admin Express IGN), précision 5 m.",
    "coverage": {
      "north": 45.06780392777273,
      "south": 44.65785668202483,
      "east": -0.2343772818092107,
      "west": -0.9217024035916317
    },
    "reference": {
      "mode": "fixed-instant",
      "label": "Unité urbaine de Bordeaux · maximum local au centroïde",
      "timeUtc": "2026-08-12T18:24:25.289Z"
    },
    "surface": {
      "resolutionMeters": 5.0,
      "observerHeightMeters": 1.7,
      "includesBuildings": true,
      "includesVegetation": true,
      "generatedAt": "2026-08-10T16:25:05.262369+00:00",
      "sourceTiers": [
        "IGN LiDAR HD",
        "MNS Correl (fallback)",
        "RGE ALTI (fallback)"
      ]
    },
    "halo": {
      "capped": false,
      "sunwardMeters": 4000.0
    },
    "tiles": {
      "scheme": "xyz",
      "tileSize": 256,
      "minZoom": 8,
      "maxZoom": 15
    },
    "attribution": "© IGN — LiDAR HD, MNS Correl et RGE ALTI · Licence Ouverte 2.0"
  },
  {
    "rank": 7,
    "code": "06701",
    "slug": "nice",
    "name": "Nice",
    "id": "uu-06701-maximum-geometry",
    "version": "uu-06701-2026-max-v1",
    "label": "Unité urbaine de Nice",
    "sourceNotes": "Composition INSEE des UU 2020 au 01/01/2026 ; contours communaux Etalab 2026 (Admin Express IGN), précision 5 m.",
    "coverage": {
      "north": 43.87665303739157,
      "south": 43.46363776102497,
      "east": 7.397905246281416,
      "west": 6.814824640279505
    },
    "reference": {
      "mode": "fixed-instant",
      "label": "Unité urbaine de Nice · maximum local au centroïde",
      "timeUtc": "2026-08-12T18:24:02.525Z"
    },
    "surface": {
      "resolutionMeters": 5.0,
      "observerHeightMeters": 1.7,
      "includesBuildings": true,
      "includesVegetation": true,
      "generatedAt": "2026-08-10T16:25:34.496813+00:00",
      "sourceTiers": [
        "IGN LiDAR HD",
        "MNS Correl (fallback)",
        "RGE ALTI (fallback)"
      ]
    },
    "halo": {
      "capped": true,
      "sunwardMeters": 15000.0
    },
    "tiles": {
      "scheme": "xyz",
      "tileSize": 256,
      "minZoom": 8,
      "maxZoom": 15
    },
    "attribution": "© IGN — LiDAR HD, MNS Correl et RGE ALTI · Licence Ouverte 2.0"
  },
  {
    "rank": 8,
    "code": "44701",
    "slug": "nantes",
    "name": "Nantes",
    "id": "uu-44701-maximum-geometry",
    "version": "uu-44701-2026-max-v1",
    "label": "Unité urbaine de Nantes",
    "sourceNotes": "Composition INSEE des UU 2020 au 01/01/2026 ; contours communaux Etalab 2026 (Admin Express IGN), précision 5 m.",
    "coverage": {
      "north": 47.36070902526704,
      "south": 47.08619281854828,
      "east": -1.361843328098814,
      "west": -1.8524430547210597
    },
    "reference": {
      "mode": "fixed-instant",
      "label": "Unité urbaine de Nantes · maximum local au centroïde",
      "timeUtc": "2026-08-12T18:20:42.009Z"
    },
    "surface": {
      "resolutionMeters": 5.0,
      "observerHeightMeters": 1.7,
      "includesBuildings": true,
      "includesVegetation": true,
      "generatedAt": "2026-08-10T16:25:54.562245+00:00",
      "sourceTiers": [
        "IGN LiDAR HD",
        "MNS Correl (fallback)",
        "RGE ALTI (fallback)"
      ]
    },
    "halo": {
      "capped": false,
      "sunwardMeters": 4000.0
    },
    "tiles": {
      "scheme": "xyz",
      "tileSize": 256,
      "minZoom": 8,
      "maxZoom": 15
    },
    "attribution": "© IGN — LiDAR HD, MNS Correl et RGE ALTI · Licence Ouverte 2.0"
  },
  {
    "rank": 9,
    "code": "00757",
    "slug": "toulon",
    "name": "Toulon",
    "id": "uu-00757-maximum-geometry",
    "version": "uu-00757-2026-max-v1",
    "label": "Unité urbaine de Toulon",
    "sourceNotes": "Composition INSEE des UU 2020 au 01/01/2026 ; contours communaux Etalab 2026 (Admin Express IGN), précision 5 m.",
    "coverage": {
      "north": 43.30041849909572,
      "south": 42.97173601911542,
      "east": 6.546308930019754,
      "west": 5.547596236611998
    },
    "reference": {
      "mode": "fixed-instant",
      "label": "Unité urbaine de Toulon · maximum local au centroïde",
      "timeUtc": "2026-08-12T18:25:13.276Z"
    },
    "surface": {
      "resolutionMeters": 5.0,
      "observerHeightMeters": 1.7,
      "includesBuildings": true,
      "includesVegetation": true,
      "generatedAt": "2026-08-10T16:26:34.600269+00:00",
      "sourceTiers": [
        "IGN LiDAR HD",
        "MNS Correl (fallback)",
        "RGE ALTI (fallback)"
      ]
    },
    "halo": {
      "capped": true,
      "sunwardMeters": 15000.0
    },
    "tiles": {
      "scheme": "xyz",
      "tileSize": 256,
      "minZoom": 8,
      "maxZoom": 15
    },
    "attribution": "© IGN — LiDAR HD, MNS Correl et RGE ALTI · Licence Ouverte 2.0"
  },
  {
    "rank": 10,
    "code": "00756",
    "slug": "douai-lens",
    "name": "Douai–Lens",
    "id": "uu-00756-maximum-geometry",
    "version": "uu-00756-2026-max-v1",
    "label": "Unité urbaine de Douai–Lens",
    "sourceNotes": "Composition INSEE des UU 2020 au 01/01/2026 ; contours communaux Etalab 2026 (Admin Express IGN), précision 5 m.",
    "coverage": {
      "north": 50.51244405359335,
      "south": 50.296877768333715,
      "east": 3.2528864852293866,
      "west": 2.6613878145487475
    },
    "reference": {
      "mode": "fixed-instant",
      "label": "Unité urbaine de Douai–Lens · maximum local au centroïde",
      "timeUtc": "2026-08-12T18:14:28.951Z"
    },
    "surface": {
      "resolutionMeters": 5.0,
      "observerHeightMeters": 1.7,
      "includesBuildings": true,
      "includesVegetation": true,
      "generatedAt": "2026-08-10T16:26:54.466845+00:00",
      "sourceTiers": [
        "IGN LiDAR HD",
        "MNS Correl (fallback)",
        "RGE ALTI (fallback)"
      ]
    },
    "halo": {
      "capped": false,
      "sunwardMeters": 4000.0
    },
    "tiles": {
      "scheme": "xyz",
      "tileSize": 256,
      "minZoom": 8,
      "maxZoom": 15
    },
    "attribution": "© IGN — LiDAR HD, MNS Correl et RGE ALTI · Licence Ouverte 2.0"
  },
  {
    "rank": 11,
    "code": "67701",
    "slug": "strasbourg",
    "name": "Strasbourg (partie française)",
    "id": "uu-67701-maximum-geometry",
    "version": "uu-67701-2026-max-v1",
    "label": "Unité urbaine de Strasbourg (partie française)",
    "sourceNotes": "Composition INSEE des UU 2020 au 01/01/2026 ; contours communaux Etalab 2026 (Admin Express IGN), précision 5 m.",
    "coverage": {
      "north": 48.69188126763106,
      "south": 48.431389586235845,
      "east": 7.840696271658917,
      "west": 7.595278974669055
    },
    "reference": {
      "mode": "fixed-instant",
      "label": "Unité urbaine de Strasbourg (partie française) · maximum local au centroïde",
      "timeUtc": "2026-08-12T18:16:15.948Z"
    },
    "surface": {
      "resolutionMeters": 5.0,
      "observerHeightMeters": 1.7,
      "includesBuildings": true,
      "includesVegetation": true,
      "generatedAt": "2026-08-10T16:27:04.679443+00:00",
      "sourceTiers": [
        "IGN LiDAR HD",
        "MNS Correl (fallback)",
        "RGE ALTI (fallback)"
      ]
    },
    "halo": {
      "capped": false,
      "sunwardMeters": 4000.0
    },
    "tiles": {
      "scheme": "xyz",
      "tileSize": 256,
      "minZoom": 8,
      "maxZoom": 15
    },
    "attribution": "© IGN — LiDAR HD, MNS Correl et RGE ALTI · Licence Ouverte 2.0"
  },
  {
    "rank": 12,
    "code": "34701",
    "slug": "montpellier",
    "name": "Montpellier",
    "id": "uu-34701-maximum-geometry",
    "version": "uu-34701-2026-max-v1",
    "label": "Unité urbaine de Montpellier",
    "sourceNotes": "Composition INSEE des UU 2020 au 01/01/2026 ; contours communaux Etalab 2026 (Admin Express IGN), précision 5 m.",
    "coverage": {
      "north": 43.754526384004876,
      "south": 43.465211928226154,
      "east": 3.995810170555257,
      "west": 3.7225642994026895
    },
    "reference": {
      "mode": "fixed-instant",
      "label": "Unité urbaine de Montpellier · maximum local au centroïde",
      "timeUtc": "2026-08-12T18:25:12.230Z"
    },
    "surface": {
      "resolutionMeters": 5.0,
      "observerHeightMeters": 1.7,
      "includesBuildings": true,
      "includesVegetation": true,
      "generatedAt": "2026-08-10T16:27:15.412537+00:00",
      "sourceTiers": [
        "IGN LiDAR HD",
        "MNS Correl (fallback)",
        "RGE ALTI (fallback)"
      ]
    },
    "halo": {
      "capped": false,
      "sunwardMeters": 6743.548800020074
    },
    "tiles": {
      "scheme": "xyz",
      "tileSize": 256,
      "minZoom": 8,
      "maxZoom": 15
    },
    "attribution": "© IGN — LiDAR HD, MNS Correl et RGE ALTI · Licence Ouverte 2.0"
  },
  {
    "rank": 13,
    "code": "00755",
    "slug": "rouen",
    "name": "Rouen",
    "id": "uu-00755-maximum-geometry",
    "version": "uu-00755-2026-max-v1",
    "label": "Unité urbaine de Rouen",
    "sourceNotes": "Composition INSEE des UU 2020 au 01/01/2026 ; contours communaux Etalab 2026 (Admin Express IGN), précision 5 m.",
    "coverage": {
      "north": 49.570935321822965,
      "south": 49.2472940204028,
      "east": 1.2494932351403387,
      "west": 0.8004835909846653
    },
    "reference": {
      "mode": "fixed-instant",
      "label": "Unité urbaine de Rouen · maximum local au centroïde",
      "timeUtc": "2026-08-12T18:16:34.970Z"
    },
    "surface": {
      "resolutionMeters": 5.0,
      "observerHeightMeters": 1.7,
      "includesBuildings": true,
      "includesVegetation": true,
      "generatedAt": "2026-08-10T16:27:37.710314+00:00",
      "sourceTiers": [
        "IGN LiDAR HD",
        "MNS Correl (fallback)",
        "RGE ALTI (fallback)"
      ]
    },
    "halo": {
      "capped": false,
      "sunwardMeters": 4000.0
    },
    "tiles": {
      "scheme": "xyz",
      "tileSize": 256,
      "minZoom": 8,
      "maxZoom": 15
    },
    "attribution": "© IGN — LiDAR HD, MNS Correl et RGE ALTI · Licence Ouverte 2.0"
  },
  {
    "rank": 14,
    "code": "00754",
    "slug": "avignon",
    "name": "Avignon",
    "id": "uu-00754-maximum-geometry",
    "version": "uu-00754-2026-max-v1",
    "label": "Unité urbaine d’Avignon",
    "sourceNotes": "Composition INSEE des UU 2020 au 01/01/2026 ; contours communaux Etalab 2026 (Admin Express IGN), précision 5 m.",
    "coverage": {
      "north": 44.189704804236634,
      "south": 43.72185344222046,
      "east": 5.3035709899320915,
      "west": 4.693117396010928
    },
    "reference": {
      "mode": "fixed-instant",
      "label": "Unité urbaine d’Avignon · maximum local au centroïde",
      "timeUtc": "2026-08-12T18:24:19.980Z"
    },
    "surface": {
      "resolutionMeters": 5.0,
      "observerHeightMeters": 1.7,
      "includesBuildings": true,
      "includesVegetation": true,
      "generatedAt": "2026-08-10T16:28:15.328817+00:00",
      "sourceTiers": [
        "IGN LiDAR HD",
        "MNS Correl (fallback)",
        "RGE ALTI (fallback)"
      ]
    },
    "halo": {
      "capped": true,
      "sunwardMeters": 15000.0
    },
    "tiles": {
      "scheme": "xyz",
      "tileSize": 256,
      "minZoom": 8,
      "maxZoom": 15
    },
    "attribution": "© IGN — LiDAR HD, MNS Correl et RGE ALTI · Licence Ouverte 2.0"
  },
  {
    "rank": 15,
    "code": "38701",
    "slug": "grenoble",
    "name": "Grenoble",
    "id": "uu-38701-maximum-geometry",
    "version": "uu-38701-2026-max-v1",
    "label": "Unité urbaine de Grenoble",
    "sourceNotes": "Composition INSEE des UU 2020 au 01/01/2026 ; contours communaux Etalab 2026 (Admin Express IGN), précision 5 m.",
    "coverage": {
      "north": 45.33360515050274,
      "south": 45.043162019630266,
      "east": 5.991661883284814,
      "west": 5.561036285735901
    },
    "reference": {
      "mode": "fixed-instant",
      "label": "Unité urbaine de Grenoble · maximum local au centroïde",
      "timeUtc": "2026-08-12T18:22:09.656Z"
    },
    "surface": {
      "resolutionMeters": 5.0,
      "observerHeightMeters": 1.7,
      "includesBuildings": true,
      "includesVegetation": true,
      "generatedAt": "2026-08-10T16:28:32.155068+00:00",
      "sourceTiers": [
        "IGN LiDAR HD",
        "MNS Correl (fallback)",
        "RGE ALTI (fallback)"
      ]
    },
    "halo": {
      "capped": true,
      "sunwardMeters": 15000.0
    },
    "tiles": {
      "scheme": "xyz",
      "tileSize": 256,
      "minZoom": 8,
      "maxZoom": 15
    },
    "attribution": "© IGN — LiDAR HD, MNS Correl et RGE ALTI · Licence Ouverte 2.0"
  },
  {
    "rank": 16,
    "code": "35701",
    "slug": "rennes",
    "name": "Rennes",
    "id": "uu-35701-maximum-geometry",
    "version": "uu-35701-2026-max-v1",
    "label": "Unité urbaine de Rennes",
    "sourceNotes": "Composition INSEE des UU 2020 au 01/01/2026 ; contours communaux Etalab 2026 (Admin Express IGN), précision 5 m.",
    "coverage": {
      "north": 48.262184194629654,
      "south": 47.977216922915474,
      "east": -1.5342862357536249,
      "west": -1.8340723953550655
    },
    "reference": {
      "mode": "fixed-instant",
      "label": "Unité urbaine de Rennes · maximum local au centroïde",
      "timeUtc": "2026-08-12T18:19:12.390Z"
    },
    "surface": {
      "resolutionMeters": 5.0,
      "observerHeightMeters": 1.7,
      "includesBuildings": true,
      "includesVegetation": true,
      "generatedAt": "2026-08-10T16:28:45.436152+00:00",
      "sourceTiers": [
        "IGN LiDAR HD",
        "MNS Correl (fallback)",
        "RGE ALTI (fallback)"
      ]
    },
    "halo": {
      "capped": false,
      "sunwardMeters": 4000.0
    },
    "tiles": {
      "scheme": "xyz",
      "tileSize": 256,
      "minZoom": 8,
      "maxZoom": 15
    },
    "attribution": "© IGN — LiDAR HD, MNS Correl et RGE ALTI · Licence Ouverte 2.0"
  },
  {
    "rank": 17,
    "code": "00753",
    "slug": "saint-etienne",
    "name": "Saint-Étienne",
    "id": "uu-00753-maximum-geometry",
    "version": "uu-00753-2026-max-v1",
    "label": "Unité urbaine de Saint-Étienne",
    "sourceNotes": "Composition INSEE des UU 2020 au 01/01/2026 ; contours communaux Etalab 2026 (Admin Express IGN), précision 5 m.",
    "coverage": {
      "north": 45.581018480103204,
      "south": 45.30865727533859,
      "east": 4.667365353727898,
      "west": 4.158785748812906
    },
    "reference": {
      "mode": "fixed-instant",
      "label": "Unité urbaine de Saint-Étienne · maximum local au centroïde",
      "timeUtc": "2026-08-12T18:22:09.938Z"
    },
    "surface": {
      "resolutionMeters": 5.0,
      "observerHeightMeters": 1.7,
      "includesBuildings": true,
      "includesVegetation": true,
      "generatedAt": "2026-08-10T16:29:05.003746+00:00",
      "sourceTiers": [
        "IGN LiDAR HD",
        "MNS Correl (fallback)",
        "RGE ALTI (fallback)"
      ]
    },
    "halo": {
      "capped": true,
      "sunwardMeters": 15000.0
    },
    "tiles": {
      "scheme": "xyz",
      "tileSize": 256,
      "minZoom": 8,
      "maxZoom": 15
    },
    "attribution": "© IGN — LiDAR HD, MNS Correl et RGE ALTI · Licence Ouverte 2.0"
  },
  {
    "rank": 18,
    "code": "37701",
    "slug": "tours",
    "name": "Tours",
    "id": "uu-37701-maximum-geometry",
    "version": "uu-37701-2026-max-v1",
    "label": "Unité urbaine de Tours",
    "sourceNotes": "Composition INSEE des UU 2020 au 01/01/2026 ; contours communaux Etalab 2026 (Admin Express IGN), précision 5 m.",
    "coverage": {
      "north": 47.53263730163864,
      "south": 47.24687246380459,
      "east": 1.1021183589112111,
      "west": 0.4872626333124949
    },
    "reference": {
      "mode": "fixed-instant",
      "label": "Unité urbaine de Tours · maximum local au centroïde",
      "timeUtc": "2026-08-12T18:19:57.355Z"
    },
    "surface": {
      "resolutionMeters": 5.0,
      "observerHeightMeters": 1.7,
      "includesBuildings": true,
      "includesVegetation": true,
      "generatedAt": "2026-08-10T16:29:31.829869+00:00",
      "sourceTiers": [
        "IGN LiDAR HD",
        "MNS Correl (fallback)",
        "RGE ALTI (fallback)"
      ]
    },
    "halo": {
      "capped": false,
      "sunwardMeters": 4000.0
    },
    "tiles": {
      "scheme": "xyz",
      "tileSize": 256,
      "minZoom": 8,
      "maxZoom": 15
    },
    "attribution": "© IGN — LiDAR HD, MNS Correl et RGE ALTI · Licence Ouverte 2.0"
  },
  {
    "rank": 19,
    "code": "00752",
    "slug": "bethune",
    "name": "Béthune",
    "id": "uu-00752-maximum-geometry",
    "version": "uu-00752-2026-max-v1",
    "label": "Unité urbaine de Béthune",
    "sourceNotes": "Composition INSEE des UU 2020 au 01/01/2026 ; contours communaux Etalab 2026 (Admin Express IGN), précision 5 m.",
    "coverage": {
      "north": 50.72066446733989,
      "south": 50.40360177204212,
      "east": 2.9272376909716415,
      "west": 2.298707122529043
    },
    "reference": {
      "mode": "fixed-instant",
      "label": "Unité urbaine de Béthune · maximum local au centroïde",
      "timeUtc": "2026-08-12T18:14:18.316Z"
    },
    "surface": {
      "resolutionMeters": 5.0,
      "observerHeightMeters": 1.7,
      "includesBuildings": true,
      "includesVegetation": true,
      "generatedAt": "2026-08-10T16:30:02.670734+00:00",
      "sourceTiers": [
        "IGN LiDAR HD",
        "MNS Correl (fallback)",
        "RGE ALTI (fallback)"
      ]
    },
    "halo": {
      "capped": false,
      "sunwardMeters": 4000.0
    },
    "tiles": {
      "scheme": "xyz",
      "tileSize": 256,
      "minZoom": 8,
      "maxZoom": 15
    },
    "attribution": "© IGN — LiDAR HD, MNS Correl et RGE ALTI · Licence Ouverte 2.0"
  },
  {
    "rank": 20,
    "code": "59701",
    "slug": "valenciennes",
    "name": "Valenciennes (partie française)",
    "id": "uu-59701-maximum-geometry",
    "version": "uu-59701-2026-max-v1",
    "label": "Unité urbaine de Valenciennes (partie française)",
    "sourceNotes": "Composition INSEE des UU 2020 au 01/01/2026 ; contours communaux Etalab 2026 (Admin Express IGN), précision 5 m.",
    "coverage": {
      "north": 50.50216760583721,
      "south": 50.246161496678866,
      "east": 3.676297910572158,
      "west": 3.173357656011953
    },
    "reference": {
      "mode": "fixed-instant",
      "label": "Unité urbaine de Valenciennes (partie française) · maximum local au centroïde",
      "timeUtc": "2026-08-12T18:14:27.503Z"
    },
    "surface": {
      "resolutionMeters": 5.0,
      "observerHeightMeters": 1.7,
      "includesBuildings": true,
      "includesVegetation": true,
      "generatedAt": "2026-08-10T16:30:23.213703+00:00",
      "sourceTiers": [
        "IGN LiDAR HD",
        "MNS Correl (fallback)",
        "RGE ALTI (fallback)"
      ]
    },
    "halo": {
      "capped": false,
      "sunwardMeters": 4000.0
    },
    "tiles": {
      "scheme": "xyz",
      "tileSize": 256,
      "minZoom": 8,
      "maxZoom": 15
    },
    "attribution": "© IGN — LiDAR HD, MNS Correl et RGE ALTI · Licence Ouverte 2.0"
  }
] as const
